### PR TITLE
Settings per menu item/Udi Support/Umbraco 7.12 support

### PR DESCRIPTION
**Pull request by ArnoldV**
This pull requests adds settings per menu item.
These settings can be added as pre-values on the Datatype, the same as Settings on a grid row work.
All the  default editors are supported:

- textstring
- textarea
- radiobuttonlist
- mediapicker
- imagepicker
- boolean
- treepicker
- treesource
- number
- multivalues

Example config:

`[
  {
    "label": "Textstring",
    "description": "Textstring description",
    "key": "textstring",
    "view": "textstring"
  },
  {
    "label": "Textarea",
    "description": "Textarea description",
    "key": "textarea",
    "view": "textarea"
  },
  {
    "label": "Radiobuttonlist",
    "description": "Radiobuttonlist description",
    "key": "radiobuttonlist",
    "view": "radiobuttonlist",
    "prevalues": [
      "value_1",
      "value_2",
      "value_3"
    ]
  },
  {
    "label": "mediapicker",
    "description": "mediapicker description",
    "key": "mediapicker",
    "view": "mediapicker"
  },
  {
    "label": "imagepicker",
    "description": "imagepicker description",
    "key": "imagepicker",
    "view": "imagepicker"
  },
  {
    "label": "boolean",
    "description": "boolean description",
    "key": "boolean",
    "view": "boolean"
  },
  {
    "label": "treepicker",
    "description": "treepicker description",
    "key": "treepicker",
    "view": "treepicker"
  },
  {
    "label": "treesource",
    "description": "treesource description",
    "key": "treesource",
    "view": "treesource"
  },
  {
    "label": "number",
    "description": "number description",
    "key": "number",
    "view": "number"
  },
  {
    "label": "multivalues",
    "description": "multivalues description",
    "key": "multivalues",
    "view": "multivalues"
  }
]`

Also this Pull requests removes menu items that are marked by "umbracoNaviHide" by default (don't think this should be optional, this is something that should 'just be handled').
They DO show in the Umbraco backend, but will have a opacity like the unpublished items, but also get a red-dotted-border around them to indicate they are hidden in navigation.

Did not properly check the umbraco/nuget package creation, there could be something there, but it seems by default all new files should be added since they are in the same location as the current ones?

### CODE REVIEW

**Comment by ArnoldV** [comment]
Updated this pull request to make .NaviHide optional instead of default removing NaviHide items.

**Comment by SudoCat** [comment]
Just tested this out on my current project, unfortunately it looks like there's a little typo in the filenames - `meganav.prevaule.controller.js` instead of `meganav.prevalue.controller.js`  (the word prevalue).

Having a deeper look through, the prevalue settings aspect doesn't seem to be anywhere near finished - the meganav.prevalue.controller.js is literally just a console.log.

Were you still working on this? It'd probably be better to rename this PR to avoid confusion.

**Comment by ArnoldV** [comment]
The whole prevalue isn't needed... Files should not be there. We have this
in production. I'll recheck tomorrow and remove them.

Arnold

On 3 May 2017, at 18:50, Robin Neal <notifications@github.com> wrote:

Just tested this out on my current project, unfortunately it looks like
there's a little typo in the filenames - meganav.prevaule.controller.js
instead of meganav.prevalue.controller.js (the word prevalue).

Having a deeper look through, the prevalue settings aspect doesn't seem to
be anywhere near finished - the meganav.prevalue.controller.js is literally
just a console.log.

Were you still working on this? It'd probably be better to rename this PR
to avoid confusion.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/thecogworks/meganav/pull/9#issuecomment-298969540>, or mute
the thread

**Comment by ArnoldV** [comment]
Aah wait! I see what is wrong. Fixing now!

**Comment by ArnoldV** [comment]
Should be working now. Sorry for incompleteness!

**Comment by SudoCat** [comment]
Huzzah! After a bit of poking, it all seems to be in great working order 👍 🙌  This is exactly what I was looking for, thanks a bunch for your hard work on this!

Although the `prevaules` controller file still needs renaming to make it work 😜 

Now hopefully Cogworks can get this pulled in.

**Comment by ArnoldV** [comment]
*ahum* filenaming *ahum*

**Comment by ArnoldV** [comment]
Updated:
- Based on the work by @SudoCat #h5yr properties are now handled in the same dialog as where you choose the url.
- Works with UDI- Based on the UDI work by @kows so now should work properly with Umbraco Cloud out-of-the-box.
- This now works with the latest Umbraco (7.12)
- Linkpicker updated to use latest Umbraco Linkpicker (includes anchor / querystring)

**Pull request closed without merging**
